inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Metrics/BlockLength:
  Exclude:
    - config/environments/*
RSpec/ExampleLength:
  Exclude:
    - spec/requests/**/*
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/requests/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/requests/**/*
    - spec/views/**/*
Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - config/**/*
    - spec/**/*
    - db/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - solargraph_helper.rb
    - db/migrate/*
Style/GlobalStdStream:
  Exclude:
    - config/**/*
Style/RedundantConstantBase:
  Exclude:
    - config/**/*
Style/RedundantFetchBlock:
  Exclude:
    - config/**/*
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
